line-length = 120
target-version="py310"

exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "site-packages",
    "venv",
]

lint.select = [
"ALL"
]
lint.ignore = [
   "ARG",
   "ANN",
   "D",
   "EM101",
   "EM102",
   "PT001",
   "PT023",
   "SIM108",
   "SIM114",
   "TRY003",
   "TCH003",
   "PLW2901",
   "RET505",
   "PLR0913",
   "UP038",
   "TCH001",
   "T201",
   "SIM103",
   "ISC003",
   "INP001",
]

[lint.per-file-ignores]
"tests/**" = ["TID252", "PLR2004", "S101"]

[lint.isort]
no-lines-before = ["local-folder"]

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"